<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tu_vgdue"
 *
 * Auto generated by Extension Builder 2013-03-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'VGDUE',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Dex, Fabian',
	'author_email' => 'david.h.vogt@gmail.com, f.m.stein@gmail.com',
	'author_company' => ', Stein & Scheibe',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>